[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
daily_fact_bot = "CyMNpNWg1aN3ohjibVPWCtdMiKgh7o98GJG8NKnr5dwR"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test:devnet"

[hooks]
