[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
daily_fact_bot = "dVwu33nvA71Dzdp1qgAinNTxpUMUBdYJ1Ue5g32SFkn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
